### ISSUE TITLE
Automate Supernova Swag with Orbit

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#146]
### Describe the creation, change or activity you'd like to see

Set up the swag operations in Orbit to trigger and send a message to Slack (#swag-requests).

### Program

Supernova

### Please categorize your Isue by selecting one or more of these types.

Operations

**Comment by jansche** [comment]
Should we move this back to To-Do and engage on it in June, then, @Kcorb95?

**Comment by Kcorb95** [comment]
I think that may be best. When does Rachelle get back? I think a better automation process would be through AirTable instead of orbit. We don't have address details in Orbit but we do in AirTable. I could do this in an hour pretty easily but we'd need to coordinate with rachelle on how they want things handled I think. @jansche

**Comment by Kcorb95** [comment]
Closing as we rely on a different swag fulfilment service now
